### ISSUE TITLE
getWaka.com isn't updating any more 

### ISSUE THREAD

**Issue by Yamgirly** [consindo/waka#128]
My current installed version of the app is from getwaka.com and is only on 2.2.0. However, the latest version of the new link, waka.app is on 2.3.0. Would I have to remove and install the new app (and re add all my bus stops) in order to get the new updates?

**Comment by consindo** [comment]
Waka uses Service Workers, so you'll need to close all tabs and the reopen in order to get the new update.

**Comment by Yamgirly** [comment]
I have

**Comment by Yamgirly** [comment]
multiple times

**Comment by Yamgirly** [comment]
issue solved, it just took a bit of time
