### ISSUE TITLE
Unable to select a stop that is so close to another stop that the icons overlap at maximum zoom.

### ISSUE THREAD

**Issue by zachbwh** [consindo/waka#147]
Basically the title, an example of this can be shown below at the Devonport ferry terminal in Auckland. I guess a solution is to either allow the user to zoom in further or to make the active stop icon transparent to click and press events. Maybe a more robust solution is to cluster them together into one icon and then you can specify which stop you actually want in a list view or something

![Screenshot_20190412-153413_Chrome](https://user-images.githubusercontent.com/15995687/56010628-81dff280-5d38-11e9-887b-13e48e790e5d.jpg)

**Comment by consindo** [comment]
Yeah, this is a tricky problem to solve. I think for now, I'll implement some sort of collision detection, and try spread stops further apart - this should work for most cases. But will have to sort something out properly for places like Manukau bus station.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/1617948/56085338-60e0e400-5e95-11e9-876d-06b16bc9af96.png">

**Comment by consindo** [comment]
https://github.com/dymajo/waka/pull/148
