### ISSUE TITLE
Realtime API still up?

### ISSUE THREAD

**Issue by citizenxnz** [consindo/waka#166]
Is the realtime API still running please?
The API docs page returns a 404 
I've tried refreshing it a number of times as per the suggestion in the recently closed issue - no change

**Comment by consindo** [comment]
Yeah, oops, we broke it in prod recently, try here: https://uat.waka.app/a/docs/

**Comment by consindo** [comment]
The docs are accurate, but you won't be able to test in browser from the above URL.

**Comment by consindo** [comment]
https://waka.app/a/docs/ is working now.
