### ISSUE TITLE
What happened to realtime data?

### ISSUE THREAD

**Issue by Yamgirly** [consindo/waka#199]
I know this is essentially a dead project at this point, but I came across an old program of mine that uses your api, but was surprised to see that there is no realtime data, and am not sure if the data being used currently is updated, for example I couldn't find the airport link bus route in auckland. Is there any intention on Waka still being maintained?

**Comment by consindo** [comment]
Oops, fixed - realtime data is now back!

**Comment by Yamgirly** [comment]
Wow, thank you for the speedy response. However only Auckland has realtime data atm. Would it be possible to add this for Christchurch and maybe wellington too?
________________________________

**Comment by consindo** [comment]
Will have a look into that - looks like Christchurch has realtime vehicle locations only, while Wellington has full realtime data.

![image](https://user-images.githubusercontent.com/1617948/189772567-edef4fc4-df1d-43a1-bf9f-9e7212b7bb14.png)

![image](https://user-images.githubusercontent.com/1617948/189772675-3fa10871-75a5-4f16-a719-ef2f5aa790e9.png)
