### ISSUE TITLE
Won't retrieve trips after midnight unless it's after midnight

### ISSUE THREAD

**Issue by consindo** [consindo/waka#23]
You're at Queen Street outside St James on a Friday Night.

11:40PM: The 267 at 11:40 shows up. It looks like the last bus home.
12AM: There's a 258 at 12AM. There's also a load of other night buses.

**Comment by consindo** [comment]
![screenshot_20160911-000542](https://cloud.githubusercontent.com/assets/1617948/18410343/b060ffae-77b3-11e6-91b8-709ee52a2414.png)

This is another issue that should be fixed with this.

**Comment by mjdavidson** [comment]
trips by stop id only returns current day. so will have to make some gypsy la la bull to get it to work

**Comment by consindo** [comment]
You'll need to adjust the query in stations line 155 I think.

**Comment by consindo** [comment]
This works now!
