### ISSUE TITLE
Pull to Refresh Station

### ISSUE THREAD

**Issue by mjdavidson** [consindo/waka#43]
https://imgur.com/gallery/CStFy
like in the photo, when you pull the list of upcoming trips a loading icon should come up and new trips should appear like in "Auckland transit"

**Comment by consindo** [comment]
It's all realtime and fancy now, polling every 10s, so no need.

**Comment by consindo** [comment]
I can't believe Benny is still giving us $5/mo.

**Comment by mjdavidson** [comment]
Aw benny, does he use it still
