### ISSUE TITLE
Add custom sub route name for Outer Link

### ISSUE THREAD

**Issue by mjdavidson** [consindo/waka#49]
like in this image it shouldn't show "University" when your on dominion road heaping toward St Luke's it should instead have the next major stop. https://at.govt.nz/ImageResizer/media/41016/map-outer_496x295.jpg?width=780

**Comment by consindo** [comment]
Too complicated to implement for little reward - we'll just rename inner and outer links to "Outer Link Clockwise" or "Inner Link Anticlockwise"
