### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by consindo** [consindo/waka#61]
API Documentation can probably be auto generated. Tests are a bit iffy, because they probably won't work too well given they run at different times of the day etc.

**Comment by consindo** [comment]
Currently in Progress: https://getwaka.com/docs/index.html

**Comment by ghost** [comment]
How can this be faster than the AT API? Doesn't it have to work through the AT API?

**Comment by consindo** [comment]
Try it out 😄 Here's more info on how things work: www.jono.nz/2017/10/08/transit-part1/

**Comment by ghost** [comment]
Thanks

**Comment by consindo** [comment]
Fixed in 560f0dd, will put online when I can get things working properly on my laptop.
