### ISSUE TITLE
Fix up Google Lighthouse errors

### ISSUE THREAD

**Issue by ghost** [consindo/waka#64]
You should have a look at fixing some of the errors shown [here](https://googlechrome.github.io/lighthouse/viewer/?gist=766cc3e8e1a3fd785636f033a82edff9).

**Comment by consindo** [comment]
Yup, most of this is #59

**Comment by ghost** [comment]
I didn't see that. Should I close this issue?

**Comment by consindo** [comment]
Nah, it's ok. Performance could definitely be better.

**Comment by consindo** [comment]
![image](https://user-images.githubusercontent.com/1617948/29799733-f2dfa29c-8cb9-11e7-8b5b-b2f234251244.png)

Mostly good enough. Should be even better in production.
