### ISSUE TITLE
Possible new colors for bus routes

### ISSUE THREAD

**Issue by mjdavidson** [consindo/waka#8]
https://at.govt.nz/media/1875309/ng_northern-guide_june-2016_web.pdf

**Comment by mjdavidson** [comment]
https://at.govt.nz/media/1785130/cg_central-guide-april-2016_webcompressed.pdf
https://at.govt.nz/media/1785128/eg_-eastern-guide-april-2016_webcompressed.pdf
https://at.govt.nz/media/1785127/sg_-southern-guide-april-2016_webcompressed.pdf
https://at.govt.nz/media/1862373/wg_western-guide_june-2016_web.pdf

**Comment by ghost** [comment]
@mjdavidson None of these links work any more.

**Comment by ghost** [comment]
Here are the up to date links:

https://at.govt.nz/media/1973813/cg_central-guide-june-2017_web.pdf
https://at.govt.nz/media/1973826/ng_northern-guide_june-2017-web.pdf
https://at.govt.nz/media/1973674/wg_western-guide_june-2017-web.pdf
https://at.govt.nz/media/1971559/eg_eastern-guide_oct-2016_web.pdf
https://at.govt.nz/media/1973408/sg_southern-guide_may-2017-web.pdf
