### ISSUE TITLE
Travel Alerts

### ISSUE THREAD

**Issue by mjdavidson** [consindo/waka#95]
Maybe by putting a footer at the bottom of the stop

**Comment by ghost** [comment]
I am assuming that you mean push notifications? And if so, how does adding a footer deal with that?

**Comment by mjdavidson** [comment]
sorry it’s notifications about travel impact due to oncoming events, roadworks, bus stop changes and motorway info. 

https://api.at.govt.nz/v2/notifications/

**Comment by ghost** [comment]
oh okay, that makes more sense

**Comment by consindo** [comment]
Duplicate of #38
