### ISSUE TITLE
Should bus stops appear on search engine results

### ISSUE THREAD

**Issue by ghost** [consindo/waka#96]
For example:
![screenshot from 2017-11-21 17-45-40](https://user-images.githubusercontent.com/15204710/33055398-520e9fea-cee4-11e7-8dbd-a10ebd3249b5.png)

or:
![screenshot from 2017-11-21 17-50-20](https://user-images.githubusercontent.com/15204710/33055451-9b25baa6-cee4-11e7-909b-32b4fadfd5a0.png)

**Comment by consindo** [comment]
yeah, why not? https://getwaka.com/s/nz-akl
