### ISSUE TITLE
https://transit.dymajo.com has an outdated version

### ISSUE THREAD

**Issue by ghost** [consindo/waka#97]
http://transit.dymajo.com still has DYMAJO Transit v1.6.1 and this could be misleading for some people.
I suggest either removing the website, or making it redirect to https://getwaka.com

**Comment by consindo** [comment]
Nah, it's actually running the same version. Service Worker has cached the old version for you. Close the tab and open it again and it'll be updated.

It does redirect to getwaka.com, but only if you don't have any stations saved. Didn't want to break things for people that have the app pinned to their home screen.

**Comment by ghost** [comment]
oh lol

**Comment by ghost** [comment]
That's not working for me @consindo

**Comment by ghost** [comment]
I'll try clearing the cache

**Comment by ghost** [comment]
Also, the favicon updated, however the page didn't???

**Comment by ghost** [comment]
Now it works
