### ISSUE TITLE
An Israeli Waka?

### ISSUE THREAD

**Issue by ghost** [consindo/waka#98]
http://finder.startupnationcentral.org/company_page/waka

Just letting you know, this seemed interesting to me

**Comment by ghost** [comment]
I checked the wayback machine and it turns out that this company used to own https://getwaka.com before you
![screenshot from 2017-11-21 18-16-30](https://user-images.githubusercontent.com/15204710/33056081-53c726d2-cee8-11e7-8620-5ee6428bfbe5.png)

**Comment by consindo** [comment]
Nice. Tel-Aviv is big for startups.
